version: '3.8'
services:
  deep-research:
    build: .
    container_name: deep-research
    env_file:
      - .env.local
    restart: unless-stopped
    # Don't expose port publicly, only to nginx
    environment:
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_KEY}
    ports:
      - "3000:3000"
    
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - deep-research
    restart: unless-stopped 